name: firebase_dart_sdk
description: A starting point for Dart libraries or applications.
version: 0.0.1+1
author: long1eu <home@long.1eu>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
#   firebase_common:
#     git:
#       url: https://github.com/putraxor/firebase_dart_sdk
#       path: firebase_common

#   firebase_database_collection:
#     git:
#       url: https://github.com/putraxor/firebase_dart_sdk
#       path: firebase_database_collection 
 
  protobuf: ^0.10.2
  grpc: ^0.6.4
  rxdart: ^0.19.0

dev_dependencies:
#   test: ^1.0.0
#   mockito: ^3.0.0
#   sqlite:
#     git: https://github.com/putraxor/dart-sqlite
